version: '3.7'
services:
  app:
    image: "tikazyq/artipub:latest"
    environment:
      MONGO_HOST: "mongo"
      ARTIPUB_API_ADDRESS: "po-api.${host}" # 后端API地址，如果安装地址不在本机，请修改为服务器IP地址+端口号（默认为3000）
#    ports:
#      - "8000:8000" # frontend
#      - "3000:3000" # backend
    depends_on:
      - mongo
    networks:
      default:
        ipv4_address: 192.168.240.10

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 192.168.240.0/27
